### ISSUE TITLE
库呢(

### ISSUE THREAD

**Issue by addpromax** [4532sde/FakeLegymRun#1]
库呢(

**Comment by 4532sde** [comment]
早写完了，但是看了看咸鱼和淘宝，好多卖里程的，现在在犹豫要不要上传QAQ

**Comment by addpromax** [comment]
不行的话卖我也可以（）我实在不想自己刷乐跑了 哈哈哈

**Comment by 4532sde** [comment]
> 不行的话卖我也可以（）我实在不想自己刷乐跑了 哈哈哈 可以加个好友吗QQ

OK，你可以通过MTIxMTcxNzczNw==联系我，或者你可以等待我整理开源早期版本，为防止滥用加了一点点限制
