### ISSUE TITLE
GG

### ISSUE THREAD

**Issue by Ch3nSir** [4532sde/FakeLegymRun#3]
好像已经更新了。。。用不了了

**Comment by Ch3nSir** [comment]
请注意，您当前使用的版本已不再支持，请前往应用商店下载最新版。

**Comment by Ch3nSir** [comment]
报这个错误

**Comment by 4532sde** [comment]
新算法逆向完了，目前没公开的意向，公开估计很快寄

**Comment by SharkyK** [comment]
> 新算法逆向完了，目前没公开的意向，公开估计很快寄

作者您好！请问可以提供一下新的代码吗，这个已经用不了了，仅自用QAQ万分感谢！

**Comment by 4532sde** [comment]
> > 新算法逆向完了，目前没公开的意向，公开估计很快寄
> 
> 作者您好！请问可以提供一下新的代码吗，这个已经用不了了，仅自用QAQ万分感谢！

我们会在9/25之前提交新的脚本，但是我们仍然不会公开算法，如果对于算法感兴趣，我们会指导部分逆向
