### ISSUE TITLE
逆向思路求助

### ISSUE THREAD

**Issue by yuuuuuuer** [4532sde/FakeLegymRun#4]
你好，我目前已经拿到3.10.0版本的dex，以及登录加密算法的so文件。
碍于汇编及逆向知识薄弱，即使有IDA作为工具，仍不太能看明白加密算法的getdykey函数过程。
是否可以向二位请教如何分析这段代码？

**Comment by 4532sde** [comment]
感谢提出issue，如果对于内部实现很感兴趣，可以留下联系方式或者从closed的issue中找到我的联系方式

**Comment by dudongboxian** [comment]
想问问pyd那个ecb的aes怎么搞

**Comment by dudongboxian** [comment]
> 你好，我目前已经拿到3.10.0版本的dex，以及登录加密算法的so文件。 碍于汇编及逆向知识薄弱，即使有IDA作为工具，仍不太能看明白加密算法的getdykey函数过程。 是否可以向二位请教如何分析这段代码？

哥们可以借你so看看吗一起研究研究？

**Comment by 4532sde** [comment]
> > 你好，我目前已经拿到3.10.0版本的dex，以及登录加密算法的so文件。 碍于汇编及逆向知识薄弱，即使有IDA作为工具，仍不太能看明白加密算法的getdykey函数过程。 是否可以向二位请教如何分析这段代码？
> 
> 哥们可以借你so看看吗一起研究研究？

直接解压libs里面的security，新的so可读性比dump出来的强
